/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Scanner;

/**
 *
 * @author Rui
 */
public class Ventana3_ProyectoP11 extends javax.swing.JFrame {
    
    ArrayList<Personaje> personajes = new ArrayList<Personaje>();
    public void add(){
        personajes.add(new Personaje("Santana", 1000.00,150.00, 300.00, 250.00,"aire"));
        personajes.add(new Personaje("Aquamen", 1000.00,100.00, 400.00, 150.00, "agua"));
        personajes.add(new Personaje("Fire Stick", 1000.00,200.00, 170.00, 300.00,"fuego"));
        personajes.add(new Personaje("Joker", 1000.00,170.00, 350.00, 120.00,"aire"));
        personajes.add(new Personaje("Lancer", 1000.00,250.00, 200.00, 100.00,"tierra"));
    }
    
    public Ventana3_ProyectoP11() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icon_logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExit = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jLabelText = new javax.swing.JLabel();
        jButtonJoker = new javax.swing.JButton();
        jButtonLancer = new javax.swing.JButton();
        jButtonAquemen = new javax.swing.JButton();
        jButtonFireStick = new javax.swing.JButton();
        jButtonNew = new javax.swing.JButton();
        jButtonSantana = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonExit.setBackground(new java.awt.Color(0, 153, 153));
        jButtonExit.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(153, 0, 0));
        jButtonExit.setText("Salida");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, -1, -1));

        jLabelTitle.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setText("¡  Q U E   C O M I E N Z E   E L   J U E G O  !");
        getContentPane().add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 720, 50));

        jLabelText.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabelText.setForeground(new java.awt.Color(255, 255, 255));
        jLabelText.setText("Seleccione a su personaje:");
        getContentPane().add(jLabelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 300, -1));

        jButtonJoker.setBackground(new java.awt.Color(0, 153, 153));
        jButtonJoker.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jButtonJoker.setForeground(new java.awt.Color(153, 0, 0));
        jButtonJoker.setText("J O K E R");
        getContentPane().add(jButtonJoker, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 240, 90));

        jButtonLancer.setBackground(new java.awt.Color(0, 153, 153));
        jButtonLancer.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jButtonLancer.setForeground(new java.awt.Color(153, 0, 0));
        jButtonLancer.setText("L A N C E R");
        getContentPane().add(jButtonLancer, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 240, 90));

        jButtonAquemen.setBackground(new java.awt.Color(0, 153, 153));
        jButtonAquemen.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jButtonAquemen.setForeground(new java.awt.Color(153, 0, 0));
        jButtonAquemen.setText("A Q U A M E N");
        jButtonAquemen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAquemenActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAquemen, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 240, 90));

        jButtonFireStick.setBackground(new java.awt.Color(0, 153, 153));
        jButtonFireStick.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jButtonFireStick.setForeground(new java.awt.Color(153, 0, 0));
        jButtonFireStick.setText("F I R E   S T I C K");
        jButtonFireStick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFireStickActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFireStick, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 240, 90));

        jButtonNew.setBackground(new java.awt.Color(0, 153, 153));
        jButtonNew.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jButtonNew.setForeground(new java.awt.Color(153, 0, 0));
        jButtonNew.setText("? ? ?");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, 240, 90));

        jButtonSantana.setBackground(new java.awt.Color(0, 153, 153));
        jButtonSantana.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jButtonSantana.setForeground(new java.awt.Color(153, 0, 0));
        jButtonSantana.setText("S A N T A N A");
        jButtonSantana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSantanaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSantana, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 240, 90));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background.jpg"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1022, 567));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonSantanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSantanaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonSantanaActionPerformed

    private void jButtonAquemenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAquemenActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonAquemenActionPerformed

    private void jButtonFireStickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFireStickActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonFireStickActionPerformed

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        Ventana4_ProyectoP1 ventana4 = new Ventana4_ProyectoP1();
        ventana4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana3_ProyectoP11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana3_ProyectoP11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana3_ProyectoP11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana3_ProyectoP11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana3_ProyectoP11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAquemen;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonFireStick;
    private javax.swing.JButton jButtonJoker;
    private javax.swing.JButton jButtonLancer;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonSantana;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelText;
    private javax.swing.JLabel jLabelTitle;
    // End of variables declaration//GEN-END:variables
}
