/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Rui
 */
public class Ventana2_ProyectoP1 extends javax.swing.JFrame {

    /**
     * Creates new form InterfazProyectoP1
     */
    public Ventana2_ProyectoP1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icon_logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExit = new javax.swing.JButton();
        jLabelInstrucciones1 = new javax.swing.JLabel();
        jButtonNext = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonExit.setBackground(new java.awt.Color(0, 153, 153));
        jButtonExit.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(153, 0, 0));
        jButtonExit.setText("S A L I D A");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, -1, -1));

        jLabelInstrucciones1.setBackground(new java.awt.Color(204, 255, 255));
        jLabelInstrucciones1.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabelInstrucciones1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInstrucciones1.setText("<html>1. Este juego esta basado en los dos juegos de pelea Super Smash Bros y Mortal Kombat<p>No queremos que nada de lo visto en estos momentos se practique en casa ni en cualquier otro lado.<p><p>2. En el modo de juego de un jugador seras tu contra la maquina, seras capaz de elegir tu combatiente mientras la maquina elegira uno al azar. \n" +
            "Cuando esten en la batalla tendras que elegir que ataque quieres hacer para que tu oponente reciba golpes y puede bajar su vida.<p><p>3. El ganador es el que quede con vida no hay mas.<p><p>4. En el modo de dos jugadores, las dos personas tendran que elegir sus combatientes y batallar hasta que quede uno\n" +
            "quede vivo, y como se dice en el mundo real... QUE GANE EL MEJOR.<p><p>5. Asi como seras capaz de elegir que combatiente quieres utilizar tambien seras capaz de crear tu propio personajecon sus propios golpes y mas.<p><p>6. Este juego esta creado por la organizacion RJPogra1 Society Project (RJPSP) y esta creado no solo por el simple\n" +
            "hecho de que valga puntos, si no por que queremos que sea el mejor proyecto que se presente en esta aula y que\n" +
            "gane los Grammys y de paso los Oscar el proximo year. (No gana el mundial por que es un proyecto y no un pais)<p><p>7. Septima y ultima regla pero no menos importante, Disfrute :D<html>");
        getContentPane().add(jLabelInstrucciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1000, 330));

        jButtonNext.setBackground(new java.awt.Color(0, 153, 153));
        jButtonNext.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jButtonNext.setForeground(new java.awt.Color(153, 0, 0));
        jButtonNext.setText("N E X T");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 500, 120, 50));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/background.jpg"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1022, 567));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        Ventana3_ProyectoP11 mainGame = new Ventana3_ProyectoP11();
        mainGame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2_ProyectoP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2_ProyectoP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2_ProyectoP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2_ProyectoP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2_ProyectoP1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelInstrucciones1;
    // End of variables declaration//GEN-END:variables
}
